services:
  api:
    container_name: neura_api_${ENV}
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    depends_on:
      - db
    image: neura_api_${ENV}
    networks:
      - neura_net
    restart: always
    env_file:
      - .env.${ENV}

  db:
    container_name: ${DB_HOST}
    image: mongo:5
    restart: always
    ports:
      - '${DB_EXPOSED_PORT}:${DB_PORT}'
    networks:
      - neura_net
    environment:
      MONGODB_DATABASE: ${DB_NAME}
    volumes:
      - ./mongo/${ENV}:/data/db
networks:
  neura_net:
