services:
  api:
    container_name: neura_api_${ENV}
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '${SERVER_PORT}:3000'
    depends_on:
      - db
    image: neura_api_${ENV}
    networks:
      - neura_net
    restart: always
    env_file:
      - .env.${ENV}

  db:
    container_name: ${DB_HOST}
    image: mongo:4.4.6
    restart: always
    ports:
      - '${DB_EXPOSED_PORT}:${DB_PORT}'
    networks:
      - neura_net
    environment:
      MONGODB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mongo/${ENV}:/data/db
networks:
  neura_net:
